#!/bin/bash -e
if [[ ! -f "/home/spark-f710da84-6604-469d-85fd-0a/tmp/uv/uv_0.6.10_linux_amd64" ]]; then
  curl -LsSf https://astral.sh/uv/0.6.10/install.sh | sh
  exec "$HOME/.local/bin/uv" "$@"
fi
exec "/home/spark-f710da84-6604-469d-85fd-0a/tmp/uv/uv_0.6.10_linux_amd64" "$@"
